Pendientes.js
		{
			'categoria': 'Restaurante',
			'nombreNegocio': 'Broaster Chicken',
			'descripcion': 'Pollo asado, pollo apanado, consomé, arróz con pollo, entre otros.',
			'Telefono': '3206125902',
			'Telefono2': '3188555669',
		},
		{
			'categoria': 'Cárnicos',
			'nombreNegocio': 'Productos cárnicos',
			'descripcion': 'Pollo campesino',
			'Telefono': '3113691402',
			'Telefono2': '-',
		},
		{
			'categoria': 'Aseo y hogar',
			'nombreNegocio': 'Cristalería y variedades SurtiHogar',
			'descripcion': 'Productos para el aseo del hogar',
			'Telefono': '3127649165',
			'Telefono2': '3146739901',
		},
		{
			'categoria': 'Aseo y hogar',
			'nombreNegocio': 'Almacén Plastiaseo ',
			'descripcion': 'Productos desechables',
			'Telefono': '3182854255',
			'Telefono2': '-',
		},
		{	
			'categoria': 'Comidas rápidas',
			'nombreNegocio': 'Productos de choclo Maizal Roceño',
			'descripcion': 'Arepas, masa, envueltos de choclo, arepa de huevo, chuzos, chorizos, jugo natural',
			'Telefono': '3155373787',
			'Telefono2': '3117156854',
		},
		{	
			'categoria': 'Comidas rápidas',
			'nombreNegocio': 'Aquí es QUINA',
			'descripcion': 'Asados y comidas rápidas',
			'Telefono': '3173135699',
			'Telefono2': '-',
		},
		{	
			'categoria': 'Comidas rápidas',
			'nombreNegocio': 'Escarchados',
			'descripcion': 'Arepa de maíz cruda, hamburguesa, salchipapa y chorizo',
			'Telefono': '3155291008',
			'Telefono2': '-',
		},
		{
			'categoria': 'Panaderia',
			'nombreNegocio': 'Panadería Rozo Pan',
			'descripcion': 'Panadería',
			'Telefono': '3147045051',
			'Telefono2': '3146186960',
		},
		{
			'categoria': 'Heladeria',
			'nombreNegocio': 'Fantasilandia Frozen',
			'descripcion': 'Heladería',
			'Telefono': '3176396825',
			'Telefono2': '-',
		},
		{
			'categoria': 'Heladeria',
			'nombreNegocio': 'Dream Heladería',
			'descripcion': 'Heladería',
			'Telefono': '3165397091',
			'Telefono2': '-',
		},
		{
			'categoria': 'Tienda',
			'nombreNegocio': 'Tienda y revueltería el Paisa',
			'descripcion': 'Productos de la canasta familiar',
			'Telefono': '3215206513',
			'Telefono2': '-',
		},